### PR TITLE
Fix #64

### LINKED ISSUE #64: Subscribe newsletter input style is broken
**Problem 1**
Text field has default iOS safari default, i.e. white background color and blue border
IMG_D0F22326D10B-1

**Solution 1**
Add css to remove default white background of text field in iOS Safari
```
background-color: transparent
border-radius: 0;
// ...
```

**Problem 2**
The position of submit button is not correct on Mac Safari and Firefox
Screenshot 2020-01-20 at 7 02 23 PM

### PR DESCRIPTION
**Pull request by mailtime-wing**
Adjust input style for firefox and safari browser. fix #64

### CODE REVIEW

File: src/components/Subscribe/style.js [hunk 1]
```diff
@@ -59,18 +62,22 @@ export const subscribe = theme => css`
 export const emailInput = theme => css`
   border: none;
   font-size: 3.2rem;
+  background-color: transparent;
+  border-radius: 0;
```
Comment (chochihim) [inline src/components/Subscribe/style.js]: put these to global style in `src/components/layout.js`

Comment (mailtime-wing) [reply src/components/Subscribe/style.js]: done.
